server:
  port: 9002
dubbo:
  registries:

    beijing:
      address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20880

  application:
    name: "dubbo-client"

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "dubbo2"